version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ~/data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
    - "8080:80"
    volumes:
    - ~/data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back_app
    image: node_app
    ports:
    - "3001:3001"
    env_file:
    - ./backend/.env
    depends_on:
    - postgres
    networks:
    - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front_app
    image: front_app
    ports:
    - "3000:3000"
    env_file:
    - ./frontend/.env
 
networks:
  postgres:
    driver: bridge
